version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - static_data:/web/static/
      - media_data:/web/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./infrastructure/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/var/html/static/
      - media_data:/var/html/media/
    depends_on:
      - web

volumes:
  db_data:
  static_data:
  media_data:
