[tool.black]
line-length = 119
include = '\.pyi?$'
exclude = '''
(
  /(
      \.git          
    | \.mypy_cache
    | \venv
    | \config
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''