[tool.black]
line-length = 119
include = '\.pyi?$'
exclude = '''
(
  /(
      \.git          
    | \.mypy_cache
    | \.venv
    | \demencia
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''